services:
    app:
        build:
            context: .docker/php/
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-7.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            WWWGROUP: '777'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql

    mysql:
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        networks:
            - sail
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: laravel
            MYSQL_USER: test
            MYSQL_PASSWORD: test

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
