version: '3.9'

services:
    mysql:
        image: mysql
        restart: always
        ports:
            -   "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: laravel
            MYSQL_USER: test
            MYSQL_PASSWORD: test
